version: '3.7'

services:
  api:
    build:
      context: back
      dockerfile: Dockerfile
    image: golfbooker/flask-python
    container_name: api
    restart: unless-stopped
    volumes:
      - back_volume:/usr/src/app
    depends_on:
      - mongodb
    networks:
      - backend

  mongodb:
    image: mongo:4.0.8
    container_name: mongodb
    restart: unless-stopped
    command: mongod
    environment:
      MONGODB_DATA_DIR: /data/db
      MONGODB_LOG_DIR: /dev/null
    volumes:
      - mongodb_volume:/data/db
    networks:
      - backend

  nginx:
    image: linuxserver/letsencrypt
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/config/nginx/nginx.conf
      - ./prod.conf:/config/nginx/site-confs/default
    environment:
      - PUID=1050
      - PGID=1050
      - EMAIL=${LETSENCRYPT_EMAIL}
      - URL=martinlabs.tech
      - SUBDOMAINS=${SUBDOMAIN}
      - ONLY_SUBDOMAINS=true
      - TZ=Australia/Melboure
    depends_on:
      - api
      - client

  client:
    image: golfbooker/react
    container_name: client
    restart: unless-stopped
    ports:
      - 3000
    depends_on:
      - api

volumes:
  back_volume:
    driver: local
  mongodb_volume:
    driver: local

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge