version: '3.7'

services:
  api:
    build:
      context: back
      dockerfile: Dockerfile
    image: golfbooker_dev/flask-python
    container_name: golfbooker_dev_api
    restart: unless-stopped
    volumes:
      - ./back:/usr/src/app
    depends_on:
      - mongodb
    environment:
      MONGODB_HOST: mongodb
    networks:
      - backend
    ports:
      - "5001:5000"

  mongodb:
    image: mongo:4.0.8
    container_name: golfbooker_dev_mongodb
    restart: unless-stopped
    command: mongod
    environment:
      MONGODB_DATA_DIR: /data/db
      MONGODB_LOG_DIR: /dev/null
    volumes:
      - ./mongodb:/data/db
    networks:
      - backend

networks:
  backend:
    driver: bridge
