version: '3.7'

services:
  api:
    build:
      context: back
      dockerfile: Dockerfile
    image: golfbooker/flask-python
    container_name: api_dev
    restart: unless-stopped
    volumes:
      - ./back:/usr/src/app
    depends_on:
      - mongodb
    networks:
      - backend
    ports:
      - "5000:5000"

  mongodb:
    image: mongo:4.0.8
    container_name: mongodb
    restart: unless-stopped
    command: mongod
    environment:
      MONGODB_DATA_DIR: /data/db
      MONGODB_LOG_DIR: /dev/null
    volumes:
      - ./mongodb:/data/db
    networks:
      - backend

  client:
    build:
      context: front
      dockerfile: Dockerfile
    image: golfbooker/react
    container_name: client
    restart: unless-stopped
    volumes:
      - ./front:/usr/src/app
      - /var/www/html/golf_front:/usr/src/app/build
    depends_on:
      - api

networks:
  backend:
    driver: bridge
